// <auto-generated />
using System;
using LomboReaderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LomboReaderAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230723190821_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LimboReaderDB")
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Authors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.BookArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Author_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleImgFile")
                        .HasColumnType("longtext");

                    b.Property<Guid>("User_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("BookArticles", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Comments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookArticle_Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("User")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Comments", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BookArticleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookArticleId");

                    b.ToTable("Genres", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles", "LimboReaderDB");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7180e255-c840-4180-9384-12d3f063e444"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("7fa1237a-1756-4ab6-a789-2d3a5330ae78"),
                            RoleName = "UserController"
                        });
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.SubGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Genre_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubGenreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubGenres", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BookArticleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BookArticleId");

                    b.ToTable("Tag", "LimboReaderDB");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLoginDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RegisterDt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", "LimboReaderDB");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6764db38-5306-4e85-a15d-7392e8422b8a"),
                            Email = "admin@ukr.net",
                            Login = "Admin",
                            Name = "Root Administrator",
                            PasswordHash = "CDE2E51D593001C6392593A3332BCEE452B61273",
                            RegisterDt = new DateTime(2023, 7, 23, 22, 8, 21, 784, DateTimeKind.Local).AddTicks(1502),
                            UserRole = "Admin"
                        });
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Genre", b =>
                {
                    b.HasOne("LomboReaderAPI.Data.Entety.BookArticle", null)
                        .WithMany("GenresList")
                        .HasForeignKey("BookArticleId");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.Tag", b =>
                {
                    b.HasOne("LomboReaderAPI.Data.Entety.BookArticle", null)
                        .WithMany("TagList")
                        .HasForeignKey("BookArticleId");
                });

            modelBuilder.Entity("LomboReaderAPI.Data.Entety.BookArticle", b =>
                {
                    b.Navigation("GenresList");

                    b.Navigation("TagList");
                });
#pragma warning restore 612, 618
        }
    }
}
